version: '3.5'

services:
  mysql-server:
    image: mysql
    container_name: "mysql-server"
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: alex
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./zabbix/mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin --default-authentication-plugin=mysql_native_password

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway 
    container_name: "zabbix-java-gateway"
    restart: unless-stopped

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql
    container_name: "zabbix-server-mysql"
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: alex
      MYSQL_ROOT_PASSWORD: 123456
      ZBX_JAVAGATEWAY: zabbix-java-gateway
    ports:
       - '10051:10051'
    restart: unless-stopped
    links: 
      - mysql-server:mysql
      - zabbix-java-gateway:zabbix-java-gateway

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: "zabbix-web-nginx-mysql"
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: alex
      MYSQL_ROOT_PASSWORD: 1234556
    ports:
      - '80:8080'
    restart: unless-stopped
    links: 
      - mysql-server:mysql
      - zabbix-server-mysql:zabbix-server

  zabbix-agent:
    image: zabbix/zabbix-agent
    container_name: "zabbix-agent"
    environment:
      ZBX_HOSTNAME: Zabbix server
      ZBX_SERVER_HOST: zabbix-server
    links: 
      - mysql-server:mysql
      - zabbix-server-mysql:zabbix-server
