version: "3.7"
   
services:
  web:
    image: alekseynalivaiko/internship:latest
<<<<<<< HEAD
	  container_name: web
=======
	container_name: web
>>>>>>> eea6a361a1d4c3227a45cbab37bb894240941aa6
    expose:
      - "8081"
    ports:
      - "80"
    deploy:
      mode: replicated
      replicas: 5
      
  app:
    image: jenkins/jenkins:latest
    container_name: app
    ports:
      - "8082:8080" 
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
<<<<<<< HEAD
	  ports:
	  - "5432:5432"
	  env_file:
=======
	ports:
	  - "5432:5432"
	env_file:
>>>>>>> eea6a361a1d4c3227a45cbab37bb894240941aa6
      - ./database.env